name: deploy-container
on:
  push:
    branches:
      - master
    paths:
      - 'packages/container/**'
defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
       
      - run: aws s3 sync dist s3://mfe-navi-dashboard/container/latest
        env:
          AWS_ACCESS_KEY_ID: AKIAQLH2ESQL7G6X4TN5
          AWS_SECRET_ACCESS_KEY: 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
          region: ap-southeast-1